Repository kudobuilder/kudo, pull requests merged in 2019-12, with the labels that each got.

#1108 Run a cleanup plan when deleting instances
  pkg/apis/kudo/v1beta1/instance_types.go
  pkg/controller/instance/instance_controller.go
  test/e2e/cli-install-uninstall/02-assert.yaml
  test/e2e/cli-install-uninstall/02-errors.yaml
  test/e2e/cli-install-uninstall/first-operator/operator.yaml
  test/e2e/cli-install-uninstall/first-operator/templates/cleanup.yaml
Labels: kind/feature

#1105 KEP-17: Pipe task implementation
  go.mod
  go.sum
  keps/0017-pipe-tasks.md
  pkg/apis/kudo/v1beta1/operatorversion_types.go
  pkg/apis/kudo/v1beta1/zz_generated.deepcopy.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_suite_test.go
  pkg/controller/instance/instance_controller_test.go
  pkg/engine/health/health.go
  pkg/engine/task/podexec/pod_exec.go
  pkg/engine/task/render.go
  pkg/engine/task/task.go
  pkg/engine/task/task_apply.go
  pkg/engine/task/task_apply_test.go
  pkg/engine/task/task_delete.go
  pkg/engine/task/task_pipe.go
  pkg/engine/task/task_pipe_test.go
  pkg/engine/task/task_test.go
  pkg/engine/workflow/engine.go
  pkg/kudoctl/packages/package.go
  pkg/test/utils/subset.go
  test/integration/upgrade-command/first-operator/operator.yaml
  test/integration/upgrade-command/first-operator/templates/configmap.yaml
  test/integration/upgrade-command/first-operator/templates/pod.yaml
  test/integration/upgrade-command/second-operator/operator.yaml
  test/integration/upgrade-command/second-operator/templates/configmap.yaml
  test/integration/upgrade-command/second-operator/templates/pod.yaml
Labels: needs review

#1133 Introduce validating admission webhook (experimental)
  Makefile
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/kudo/v1beta1/instance_validator.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init/manager.go
  pkg/kudoctl/cmd/init/prereqs.go
  pkg/kudoctl/cmd/init/webhook.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns-default.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kube/config.go
  pkg/util/kudo/validator.go
Labels: release-highlight

#1145 Install GolangCI-Lint as a binary
  Makefile
  go.mod
  go.sum
  hack/install-golangcilint.sh
  tools.go
Labels: component/linter

#1146 Disallow only spec updates for now
  pkg/apis/kudo/v1beta1/instance_validator.go
  pkg/apis/kudo/v1beta1/instance_validator_test.go
Labels: component/webhook

#1045 KEP-20: Manual plan execution
  keps/0020-manual-plan-execution.md
  keps/README.md
Labels: kind/kep

#1159 Add `verifier.Result` to encapsulate verification errors and warnings handling
  pkg/kudoctl/cmd/package_verify.go
  pkg/kudoctl/cmd/verify/verify.go
  pkg/kudoctl/cmd/verify/verify_test.go
  pkg/kudoctl/packages/verifier/result.go
  pkg/kudoctl/packages/verifier/template/verify_parameters.go
  pkg/kudoctl/packages/verifier/template/verify_parameters_test.go
  pkg/kudoctl/packages/verifier/template/verify_references.go
  pkg/kudoctl/packages/verifier/template/verify_references_test.go
  pkg/kudoctl/packages/verifier/types.go
Labels: kind/cleanup

#1157 Enable additional linters
  .golangci.yml
  pkg/controller/instance/instance_controller_suite_test.go
  pkg/engine/task/podexec/pod_exec.go
  pkg/engine/task/task_apply_test.go
  pkg/kudoctl/clog/log_test.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/util/kudo/kudo_test.go
  pkg/test/utils/kubernetes.go
Labels: component/linter

#1169 Wait for the entire assert timeout for resources to be deleted.
  pkg/test/step.go
Labels: component/testing

#1173 Include phase strategy in plan status output
  pkg/kudoctl/cmd/plan/plan_status.go
  pkg/kudoctl/cmd/plan/plan_status_test.go
Labels: component/kudoctl

#1202 Windows CLI is not currently built for KUDO so do not include in Krew manifest.
  hack/generate_krew.sh
Labels: component/generator

#1203 Remove obsolete linting steps from the styleguide
  STYLEGUIDE.md
Labels: kind/documentation

#1193 Chore: Update direct dependencies to their latest versions
  go.mod
  go.sum
  pkg/test/harness.go
  pkg/test/utils/kubernetes.go
Labels: dependencies

#1217 Refactor KinD usage in test harness and allow to add (local) containers
  pkg/apis/kudo/v1beta1/test_types.go
  pkg/test/harness.go
  pkg/test/harness_test.go
  pkg/test/kind.go
  pkg/test/kind_integration_test.go
  pkg/test/utils/docker.go
Labels: component/testing

#1227 Remove unnecessary accidental debug logging from test harness
  pkg/test/utils/kubernetes.go
Labels: component/testing, kind/bug
