Repository kudobuilder/kudo, pull requests merged in 2019-02, with the labels that each got.

#100 Allow scaling of Deployments and StatefulSets
  config/samples/kafka-instance.yaml
  pkg/controller/planexecution/planexecution_controller.go
Labels: component/operator, frameworks/definition, kind/bug, priority/critical, release-blocker

#106 Adjust OWNERS to match the current state of the repository
  OWNERS
  OWNERS_ALIASES
Labels: needs review, priority/critical

#110 Added MySQL demo video and fixed typos
  docs/Backups.md
Labels: kind/documentation

#130 [KEP 0001] KUDO Enhancement Proposal Process - Update
  keps/0001-kep-process.md
Labels: kind/kep

#129 [KEP 0000] Added PR naming convention to template
  keps/0000-kep-template.md
Labels: kind/kep

#134 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/documentation

#133 Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation

#135 Delete draft-0003-kep-cli.md
  keps/draft-0003-kep-cli.md
Labels: kind/kep
