Repository kudobuilder/kudo, pull requests merged in 2019-04, with the labels that each got.

#168 Adding kubectl version 1.12 to pre-requisites
  README.md
  docs/cli.md
Labels: kind/documentation

#170 Enhancing the details around first build
  README.md
Labels: kind/documentation

#177 Fix the formatting script
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/util/check/check.go
  pkg/kudoctl/util/check/check_test.go
  pkg/kudoctl/util/github/client.go
  pkg/kudoctl/util/github/client_test.go
  pkg/kudoctl/util/github/credential.go
  pkg/kudoctl/util/github/credential_test.go
  pkg/kudoctl/util/helpers/helpers.go
  pkg/kudoctl/util/helpers/helpers_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
  test/formatting.sh
Labels: kind/cleanup, kind/infrastructure

#182 Happy Linter!!
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/cmd/install_test.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/util/check/check.go
  pkg/kudoctl/util/github/client.go
  pkg/kudoctl/util/github/client_test.go
  pkg/kudoctl/util/helpers/helpers.go
  pkg/kudoctl/util/helpers/helpers_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: kind/cleanup

#196 Fix inline JSON struct tags
  config/crds/kudo_v1alpha1_framework.yaml
  config/crds/kudo_v1alpha1_frameworkversion.yaml
  config/crds/kudo_v1alpha1_instance.yaml
  config/crds/kudo_v1alpha1_planexecution.yaml
  pkg/apis/kudo/v1alpha1/framework_types.go
  pkg/apis/kudo/v1alpha1/frameworkversion_types.go
  pkg/apis/kudo/v1alpha1/instance_types.go
  pkg/apis/kudo/v1alpha1/planexecution_types.go
Labels: kind/bug

#22 Comparion between tools
  docs/Comparison.md
Labels: kind/documentation, priority/high

#166 added version support to Makefile, Dockerfile, Manager with ldflags
  Dockerfile
  Makefile
  cmd/manager/main.go
  config/default/manager_image_patch.yaml
  docs/cli.md
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/version.go
  pkg/version/base.go
  pkg/version/version.go
  version/version.go
Labels: component/kudoctl

#186 Adding CODEOWNERS file
  .github/CODEOWNERS
Labels: kind/documentation
