Repository kudobuilder/kudo, pull requests merged in 2019-10, with the labels that each got.

#875 Add a task for blog post to RELEASE.md
  RELEASE.md
Labels: kind/documentation

#904 Add API Extensions v1beta1 to scheme
  cmd/manager/main.go
Labels: kind/enhancement

#905 add apiextensionsv1beta1 to scheme (#904)
  cmd/manager/main.go
Labels: backport

#932 Include CRDs in the -o yaml --dry-run
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
Labels: backport

#936 Do not use strategicmergepatch for CRDs
  pkg/controller/instance/plan_execution_engine.go
  test/integration/install-existing-crds-in-operator/00-assert.yaml
  test/integration/install-existing-crds-in-operator/00-install-operator.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/operator.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/params.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/templates/crd.yaml
Labels: Needs Back-port

#937 Do not use strategicmergepatch for CRDs
  pkg/controller/instance/plan_execution_engine.go
  test/integration/install-existing-crds-in-operator/00-assert.yaml
  test/integration/install-existing-crds-in-operator/00-install-operator.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/operator.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/params.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/templates/crd.yaml
Labels: backport

#931 Plan status should show last executed plan, not just active plan
  pkg/apis/kudo/v1alpha1/instance_types.go
  pkg/apis/kudo/v1alpha1/instance_types_test.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/plan_execution_engine.go
  pkg/controller/instance/plan_execution_engine_test.go
  pkg/kudoctl/cmd/plan/plan_status.go
Labels: Needs Back-port

#944 Plan status should show last executed plan, not just active plan
  pkg/apis/kudo/v1alpha1/instance_types.go
  pkg/apis/kudo/v1alpha1/instance_types_test.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/plan_execution_engine.go
  pkg/controller/instance/plan_execution_engine_test.go
  pkg/kudoctl/cmd/plan/plan_status.go
Labels: backport

#954 Handle unknown types as unstructured
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/test/harness.go
  pkg/test/utils/dynamicrestmapper.go
  pkg/util/template/template.go
  pkg/util/template/template_test.go
  test/integration/operator-with-custom-crd/00-assert.yaml
  test/integration/operator-with-custom-crd/00-install-crd.yaml
  test/integration/operator-with-custom-crd/01-assert.yaml
  test/integration/operator-with-custom-crd/01-install.yaml
  test/integration/operator-with-custom-crd/operator/operator.yaml
  test/integration/operator-with-custom-crd/operator/params.yaml
  test/integration/operator-with-custom-crd/operator/templates/sm.yaml
Labels: Needs Back-port

#961 Fix plan history bug
  pkg/kudoctl/cmd/plan/plan_history.go
Labels: Needs Back-port

#969 Backport of fixes to TestGetLastExecutedPlanStatus
  pkg/apis/kudo/v1alpha1/instance_types.go
  pkg/apis/kudo/v1alpha1/instance_types_test.go
Labels: backport

#968 Handle unknown types as unstructured (#954)
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/test/harness.go
  pkg/test/utils/dynamicrestmapper.go
  pkg/util/template/template.go
  pkg/util/template/template_test.go
  test/integration/operator-with-custom-crd/00-assert.yaml
  test/integration/operator-with-custom-crd/00-install-crd.yaml
  test/integration/operator-with-custom-crd/01-assert.yaml
  test/integration/operator-with-custom-crd/01-install.yaml
  test/integration/operator-with-custom-crd/operator/operator.yaml
  test/integration/operator-with-custom-crd/operator/params.yaml
  test/integration/operator-with-custom-crd/operator/templates/sm.yaml
Labels: backport

#967 Backport of plan history fix on unknown instance
  pkg/kudoctl/cmd/plan/plan_history.go
Labels: backport

#856 Introduce the 'kudo uninstall' command
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/uninstall.go
  pkg/kudoctl/cmd/uninstall_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
  test/e2e/.gitkeep
  test/e2e/cli-install-uninstall/00-assert.yaml
  test/e2e/cli-install-uninstall/00-install.yaml
  test/e2e/cli-install-uninstall/02-errors.yaml
  test/e2e/cli-install-uninstall/02-uninstall.yaml
Labels: kind/feature, size/L

#984 init: handle only "kudo-system" namespace
  pkg/kudoctl/cmd/init/prereqs.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns-default.yaml.golden
Labels: Hacktoberfest

#990 Fix typos
  keps/0015-repository-management.md
  pkg/kudoctl/clog/log.go
  pkg/kudoctl/cmd/repo_context.go
  pkg/kudoctl/util/repo/repo.go
  pkg/test/case_test.go
  pkg/test/test_data/with-overrides/03-pod.yaml
Labels: Hacktoberfest

#987 Chore: Remove usage of deprecated packages
  cmd/manager/main.go
  pkg/apis/kudo/v1alpha1/register.go
Labels: kind/cleanup

#985 Simplify array construction
  pkg/kudoctl/cmd/init/prereqs.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/test/harness_test.go
Labels: kind/cleanup

#960 Make Instance name deterministic
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/packages/package.go
  pkg/kudoctl/packages/package_test.go
  pkg/kudoctl/packages/testdata/zk-crd-golden1/instance.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/instance.golden
Labels: release-highlight

#970 User-configurable request timeouts
  pkg/kudoctl/cmd/get/get.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/uninstall.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/env/environment.go
  pkg/kudoctl/env/environment_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: Hacktoberfest

#994 Setup golangci-lint as default linter framework
  .circleci/config.yml
  .golangci.yml
  .pre-commit-config.yaml
  Makefile
  hack/check_formatting.sh
  keps/0004-add-testing-infrastructure.md
Labels: ci, kind/enhancement, kind/infrastructure

#991 Refactor functions to install/upgrade package resources into 'kudo' package
  go.mod
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/cmd/uninstall_test.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/cmd/upgrade_test.go
  pkg/kudoctl/packages/package.go
  pkg/kudoctl/packages/package_manager.go
  pkg/kudoctl/packages/package_test.go
  pkg/kudoctl/util/kudo/install.go
  pkg/kudoctl/util/kudo/install_test.go
  pkg/kudoctl/util/kudo/resources.go
  pkg/kudoctl/util/kudo/upgrade.go
  pkg/kudoctl/util/kudo/upgrade_test.go
Labels: kind/cleanup, kind/enhancement

#1006 chore: Update 'controller-tools'
  go.mod
  go.sum
Labels: component/controller

#1004 Fix incorrect case of 'sprig' import
  go.mod
  go.sum
  pkg/engine/renderer/engine.go
Labels: kind/cleanup
