Repository kudobuilder/kudo, pull requests merged in 2019-06, with the labels that each got.

#282 Make deploy to print out install yaml files
  CONTRIBUTING.md
  Makefile
  config/kustomization.yaml
  config/manager/manager.yaml
  config/manager_image_patch.yaml
  config/manager_image_patch.yaml-e
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  docs/getting-started.md
  hack/update_manifests.sh
Labels: needs-release-notes

#286 Improve KEP-0009
  keps/0009-operator-toolkit.md
Labels: kep/9, kind/documentation

#283 Use Helm-style parameters for `kudoctl kudo install` command
  go.mod
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install_test.go
Labels: component/kudoctl, kind/enhancement, release-highlight

#298 CLI docs improvements
  docs/cli.md
Labels: kind/documentation

#300 Get rid of .git-credentials and switch to GCS
  .circleci/config.yml
  CONTRIBUTING.md
  docs/cli.md
  docs/getting-started.md
  docs/repository.md
  go.mod
  go.sum
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/util/check/check.go
  pkg/kudoctl/util/check/check_test.go
  pkg/kudoctl/util/github/client.go
  pkg/kudoctl/util/github/client_test.go
  pkg/kudoctl/util/github/credential.go
  pkg/kudoctl/util/github/credential_test.go
  pkg/kudoctl/util/helpers/helpers.go
  pkg/kudoctl/util/helpers/helpers_test.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/repo_client.go
  pkg/kudoctl/util/repo/repo_framework.go
  pkg/kudoctl/util/repo/repo_index.go
  pkg/kudoctl/util/vars/vars.go
  test/run_tests.sh
Labels: kep/10, kep/3

#314 Blogpost: Fixing homebrew tap cmd
  site/content/posts/announcing-kudo-0.2.0.md
Labels: kind/documentation

#315 Making code easier to read
  docs/repository.md
  pkg/kudoctl/cmd/install/install.go
Labels: kind/cleanup

#317 Update to Release Process
  RELEASE.md
Labels: kind/documentation

#248 [KEP-0010] KUDO Package Manager
  keps/0010-package-manager.md
Labels: kind/kep

#329 Clean up comments
  pkg/apis/kudo/v1alpha1/frameworkversion_types.go
  pkg/apis/kudo/v1alpha1/frameworkversion_types_test.go
  pkg/apis/kudo/v1alpha1/instance_types.go
  pkg/apis/kudo/v1alpha1/planexecution_types.go
  pkg/controller/frameworkversion/frameworkversion_controller.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/planexecution/planexecution_controller.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/repo/repo.go
  pkg/util/health/ready.go
Labels: kind/documentation

#339 Refactored install parameters
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
Labels: kind/cleanup

#324 Improve getting started and contributing docs
  CONTRIBUTING.md
  docs/getting-started.md
Labels: kind/documentation

#372 Extract method from package processing
  pkg/kudoctl/util/repo/package.go
Labels: kind/cleanup
