Repository kudobuilder/kudo, pull requests merged in 2019-09, with the labels that each got.

#746 Update controller dependencies
  go.mod
  go.sum
  pkg/test/step.go
  pkg/test/utils/kubernetes.go
Labels: approved, kind/cleanup, lgtm, size/M

#749 switching maintainer back to 0.5.0 release and adding marshaling tests
  pkg/bundle/operator.go
  pkg/kudoctl/util/repo/index.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/testdata/flink-index.yaml.golden
Labels: approved, kind/bug, size/M

#751 kudo init client side
  pkg/bundle/operator.go
  pkg/kudoctl/cmd/get.go
  pkg/kudoctl/cmd/get/get.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/plan/plan_status.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/env/environoment.go
  pkg/kudoctl/env/environoment_test.go
  pkg/kudoctl/kudohome/home.go
  pkg/kudoctl/kudohome/home_test.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/repo_test.go
  pkg/kudoctl/util/repo/testdata/repositories.yaml.golden
Labels: approved, needs-kind, size/XXL

#758 Uses Repo Name in kudo install and upgrade
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install_test.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/cmd/upgrade_test.go
  pkg/kudoctl/env/environoment.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/repo_operator.go
  pkg/kudoctl/util/repo/repo_test.go
Labels: approved, kind/feature, size/L

#757 Repo Add, Remove, List and Context Features
  go.mod
  go.sum
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install_test.go
  pkg/kudoctl/cmd/repo.go
  pkg/kudoctl/cmd/repo_add.go
  pkg/kudoctl/cmd/repo_add_test.go
  pkg/kudoctl/cmd/repo_context.go
  pkg/kudoctl/cmd/repo_context_test.go
  pkg/kudoctl/cmd/repo_list.go
  pkg/kudoctl/cmd/repo_list_test.go
  pkg/kudoctl/cmd/repo_remove.go
  pkg/kudoctl/cmd/repo_remove_test.go
  pkg/kudoctl/cmd/testdata/repo-list.golden
  pkg/kudoctl/cmd/testdata/skip-check-add-list.golden
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/update_test.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/repo_operator.go
Labels: approved, kind/feature, size/XL

#754 Proposal: Support calling out to arbitrary commands in the test harness.
  keps/0008-operator-testing.md
Labels: approved, kind/kep, lgtm, retest-not-required-docs-only, size/S

#771 brew is deprecated and replaced by a brews list
  .goreleaser.yml
Labels: approved, needs-kind, size/M

#773 Collect test metadata in integration tests
  .circleci/config.yml
  Makefile
  test/run_tests.sh
Labels: approved, kind/enhancement, needs-ok-to-test, size/XS

#788 Implement test commands feature
  .gitignore
  Makefile
  go.sum
  keps/0008-operator-testing.md
  pkg/apis/kudo/v1alpha1/test_types.go
  pkg/test/harness.go
  pkg/test/step.go
  pkg/test/test_data/cli-test/01-assert.yaml
  pkg/test/test_data/cli-test/01-patch.yaml
  pkg/test/utils/kubernetes.go
  pkg/test/utils/kubernetes_test.go
Labels: approved, kind/test, size/L

#782 Nit: Remove the trailing period after printing $KUDO_HOME
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init_test.go
Labels: approved, kind/cleanup, lgtm, size/XS

#793 Lint shell scripts and ensure consistency
  hack/check_formatting.sh
  hack/generate_krew.sh
  hack/update_codegen.sh
  hack/update_manifests.sh
  test/run_tests.sh
Labels: approved, kind/cleanup, lgtm, size/M

#791 Bumping go version to 1.13 for builds and tests
  .circleci/config.yml
  Dockerfile
  build/test-images.sh
  test/Dockerfile
Labels: approved, needs-kind, size/S

#744 Remove broken link to getting started GIF
  README.md
Labels: approved, kind/cleanup, kind/documentation, retest-not-required-docs-only, size/XS

#785 fix broken link to getting started
  README.md
Labels: approved, needs-kind, needs-ok-to-test, retest-not-required-docs-only, size/XS

#786 Remove make manifest
  .gitignore
  Makefile
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  hack/update_manifests.sh
Labels: approved, needs-kind, size/L

#787 Fixing repo command short message
  pkg/kudoctl/cmd/repo.go
Labels: approved, needs-kind, size/S

#762 Richer Maintainer Metadata
  config/crds/kudo_v1alpha1_operator.yaml
  config/samples/first-operator/operator.yaml
  go.sum
  pkg/apis/kudo/v1alpha1/operator_types.go
  pkg/apis/kudo/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/operator.go
  pkg/kudoctl/bundle/bundle.go
  pkg/kudoctl/bundle/testdata/zk-crd-golden1/operator.golden
  pkg/kudoctl/bundle/testdata/zk-crd-golden2/operator.golden
  pkg/kudoctl/bundle/testdata/zk.tar.gz
  pkg/kudoctl/bundle/testdata/zk/operator.yaml
  pkg/kudoctl/cmd/init/crds.go
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/cmd/testdata/repo-list.golden
  pkg/kudoctl/cmd/testdata/skip-check-add-list.golden
  pkg/kudoctl/util/repo/index.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/testdata/repositories.yaml.golden
  test/integration/cli-install/cli-install-operator/operator.yaml
  test/integration/upgrade-command/first-operator/operator.yaml
  test/integration/upgrade-command/second-operator/operator.yaml
Labels: approved, kind/cleanup, size/L

#799 Fix flake in operator-in-operator test
  pkg/controller/instance/instance_controller.go
  pkg/controller/planexecution/planexecution_controller.go
Labels: approved, needs-kind, size/M

#815 Backport (0.6) Bug Fix: Init YAML Generation (#813)
  pkg/kudoctl/cmd/init/crds.go
  pkg/kudoctl/cmd/init/prereqs.go
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
Labels: approved, needs-kind, size/S

#814 Backport (0.6): Proposal to print out events after finishing test run (#797)
  pkg/test/case.go
Labels: approved, needs-kind, size/M

#759 Plan execution logic extraction covered by first unit tests
  go.mod
  pkg/controller/planexecution/apply_conventions.go
  pkg/controller/planexecution/plan_execution_engine.go
  pkg/controller/planexecution/plan_execution_engine_test.go
  pkg/controller/planexecution/planexecution_controller.go
  pkg/util/health/ready.go
  test/integration/step-delete/00-install-instance.yaml
Labels: approved, needs-kind, size/XL

#801 Repo Index Merge
  pkg/kudoctl/bundle/bundle.go
  pkg/kudoctl/bundle/finder/bundle_finder.go
  pkg/kudoctl/bundle/package_test.go
  pkg/kudoctl/bundle/tar_test.go
  pkg/kudoctl/bundle/testdata/zk.tgz
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/repo.go
  pkg/kudoctl/cmd/repo_index.go
  pkg/kudoctl/cmd/repo_index_test.go
  pkg/kudoctl/cmd/testdata/index.yaml
  pkg/kudoctl/cmd/testdata/index.yaml.golden
  pkg/kudoctl/cmd/testdata/merge-index.yaml.golden
  pkg/kudoctl/cmd/testdata/merge.yaml
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/util/repo/index.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/kudoctl/util/repo/repo_operator.go
Labels: approved, needs-kind, size/L

#820 Add Master releases via Github Actions
  .github/workflows/release-on-master.yml
Labels: approved, kind/enhancement, lgtm, size/M

#823 Updates current-time to published version
  .github/workflows/release-on-master.yml
Labels: approved, kind/cleanup, lgtm, size/XS

#821 BUGFIX: repo index --url-repo
  pkg/kudoctl/cmd/repo_index.go
Labels: approved, kind/bug, size/XS

#824 CLI cleanup
  pkg/kudoctl/cmd/get.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/package.go
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/cmd/repo.go
  pkg/kudoctl/cmd/repo_add.go
  pkg/kudoctl/cmd/repo_context.go
  pkg/kudoctl/cmd/repo_index.go
  pkg/kudoctl/cmd/repo_list.go
  pkg/kudoctl/cmd/repo_remove.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/test.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/cmd/version.go
Labels: approved, kind/cleanup, size/L

#807 Add error handling where it was missing (excluding tests)
  pkg/controller/instance/instance_controller.go
  pkg/controller/planexecution/apply_conventions.go
  pkg/kudoctl/bundle/bundle.go
  pkg/kudoctl/bundle/package.go
  pkg/kudoctl/bundle/tar.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/repo_index.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/env/environoment.go
  pkg/kudoctl/files/file.go
  pkg/kudoctl/util/repo/index.go
  pkg/test/case.go
  pkg/test/harness.go
  pkg/test/utils/kubernetes.go
  pkg/test/utils/testing.go
Labels: approved, kind/bug, kind/cleanup, size/L

#794 Log a timeout that is going to be used for the suite
  pkg/test/harness.go
Labels: approved, needs-kind, size/XS

#833 Cleanup controller registration to the runtime 0.2.0
  .github/CODEOWNERS
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/operator/operator_controller.go
  pkg/controller/operatorversion/operatorversion_controller.go
  pkg/test/harness.go
  pkg/webhook/webhook.go
Labels: kind/cleanup

#834 Get rid of word bundle and use package everywhere
  keps/0009-operator-toolkit.md
  pkg/bundle/operator.go
  pkg/kudoctl/bundle/finder/bundle_finder.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/cmd/package.go
  pkg/kudoctl/cmd/package_test.go
  pkg/kudoctl/cmd/repo_index_test.go
  pkg/kudoctl/packages/finder/package_finder.go
  pkg/kudoctl/packages/finder/package_finder_test.go
  pkg/kudoctl/packages/package.go
  pkg/kudoctl/packages/package_manager.go
  pkg/kudoctl/packages/package_test.go
  pkg/kudoctl/packages/tar.go
  pkg/kudoctl/packages/tar_test.go
  pkg/kudoctl/packages/testdata/zk-crd-golden1/instance.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden1/operator.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden1/operatorversion.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/instance.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/operator.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/operatorversion.golden
  pkg/kudoctl/packages/testdata/zk.tgz
  pkg/kudoctl/packages/testdata/zk/operator.yaml
  pkg/kudoctl/packages/testdata/zk/params.yaml
  pkg/kudoctl/packages/testdata/zk/templates/pdb.yaml
  pkg/kudoctl/packages/testdata/zk/templates/services.yaml
  pkg/kudoctl/packages/testdata/zk/templates/statefulset.yaml
  pkg/kudoctl/packages/testdata/zk/templates/validation.yaml
  pkg/kudoctl/util/repo/index.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/kudoctl/util/repo/repo_operator.go
Labels: kind/cleanup

#819 KEP-0017 Pipe Tasks
  keps/0017-pipe-tasks.md
Labels: kind/kep, retest-not-required-docs-only, size/L

#836 Kubernetes Version Server Check For Kudo Install
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
  pkg/version/version.go
  pkg/version/version_test.go
  test/integration/upgrade-command/first-operator/operator.yaml
  test/integration/upgrade-command/second-operator/operator.yaml
Labels: release-highlight

#830 KEP-0018 Controller Redesign
  keps/0018-controller-overhaul.md
Labels: kind/kep

#844 Remove a nil-dereference
  pkg/controller/planexecution/planexecution_controller.go
Labels: kind/cleanup

#867 Add 'errors' file handling to test harness
  pkg/test/step.go
  pkg/test/step_test.go
  test/integration/first-operator-test/01-errors.yaml
Labels: component/testing, kind/enhancement

#854 Improved KEP-0017 design
  keps/0017-pipe-tasks.md
Labels: do-not-merge/hold

#870 Fix kudo init on Kubernetes 1.16
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init/manager.go
Labels: kind/bug, priority/critical

#882 Add shorthand `-n` for `--namespace`
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/env/environoment.go
Labels: Hacktoberfest, kind/enhancement
