Repository kudobuilder/kudo, pull requests merged in 2019-07, with the labels that each got.

#488 Adding Ability to MergePatch CRDs properly
  pkg/controller/planexecution/planexecution_controller.go
  test/integration/create-operator-in-operator/00-dream.yaml
  test/integration/create-operator-in-operator/01-assert.yaml
  test/integration/create-operator-in-operator/01-install.yaml
Labels: component/operator, kind/bug

#546 Adding Test for Parameter Parsing within Operators
  test/integration/parse-param-operator-in-operator/00-dream.yaml
  test/integration/parse-param-operator-in-operator/01-assert.yaml
  test/integration/parse-param-operator-in-operator/01-install.yaml
  test/manifests/test-operator.yaml
Labels: kind/infrastructure

#545 Change StringVar to StringVarP for version. Fixes #544
  pkg/kudoctl/cmd/install.go
Labels: kind/bug

#553 Refactoring of "get instances" CLI command
  pkg/kudoctl/cmd/get.go
  pkg/kudoctl/cmd/get/get.go
  pkg/kudoctl/cmd/get/get_test.go
  pkg/kudoctl/cmd/get/instances.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: component/kudoctl

#566 Switch CRD version reference to the next release
  .circleci/config.yml
  docs/deployment/20-deployment.yaml
Labels: kind/cleanup

#504 Add integration tests for InstanceController
  test/integration/instance-controller-param-change-custom-trigger/00-assert.yaml
  test/integration/instance-controller-param-change-custom-trigger/00-setup.yaml
  test/integration/instance-controller-param-change-custom-trigger/01-assert.yaml
  test/integration/instance-controller-param-change-custom-trigger/01-update-instance.yaml
  test/integration/instance-controller-param-change-fallback-to-deploy/00-assert.yaml
  test/integration/instance-controller-param-change-fallback-to-deploy/00-setup.yaml
  test/integration/instance-controller-param-change-fallback-to-deploy/01-assert.yaml
  test/integration/instance-controller-param-change-fallback-to-deploy/01-update-instance.yaml
  test/integration/instance-controller-param-change-no-trigger/00-assert.yaml
  test/integration/instance-controller-param-change-no-trigger/00-setup.yaml
  test/integration/instance-controller-param-change-no-trigger/01-assert.yaml
  test/integration/instance-controller-param-change-no-trigger/01-update-instance.yaml
  test/integration/instance-controller-upgrade-fallback-to-deploy/00-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-deploy/00-setup.yaml
  test/integration/instance-controller-upgrade-fallback-to-deploy/01-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-deploy/01-upgrade-instance.yaml
  test/integration/instance-controller-upgrade-fallback-to-update/00-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-update/00-setup.yaml
  test/integration/instance-controller-upgrade-fallback-to-update/01-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-update/01-upgrade-instance.yaml
  test/integration/instance-controller-upgrade/00-assert.yaml
  test/integration/instance-controller-upgrade/00-setup.yaml
  test/integration/instance-controller-upgrade/01-assert.yaml
  test/integration/instance-controller-upgrade/01-upgrade-instance.yaml
Labels: component/testing

#571 Add Build IDs to gorelease Release Builds
  .goreleaser.yml
Labels: ci, kind/bug

#579 Makefile build info should be identical to goreleaser build info
  Makefile
Labels: Needs Back-port, component/kudoctl, kind/bug

#569 adding dev and release branch details
  RELEASE.md
Labels: kind/cleanup, kind/documentation

#575 Use kubeconfig flag set at root for subcommands
  go.mod
  go.sum
  pkg/kudoctl/cmd/get.go
  pkg/kudoctl/cmd/get/get.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/plan/plan_status.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/util/check/check.go
  pkg/kudoctl/util/check/check_test.go
Labels: component/kudoctl

#587 Fix operator upgrades
  pkg/controller/planexecution/planexecution_controller.go
  test/integration/patch/00-assert.yaml
  test/integration/patch/01-assert.yaml
Labels: kind/bug, priority/critical

#596 Respect namespaces if they are set in test harness.
  keps/0008-operator-testing.md
  pkg/test/step_test.go
  pkg/test/utils/kubernetes.go
  pkg/test/utils/kubernetes_test.go
Labels: component/testing, kind/feature

#598 --start-control-plane no longer implies --start-kudo
  pkg/kudoctl/cmd/test.go
  pkg/test/harness.go
Labels: component/testing, kind/cleanup

#593 Allow overriding the test parallelism.
  kudo-test.yaml
  pkg/apis/kudo/v1alpha1/test_types.go
  pkg/kudoctl/cmd/test.go
  pkg/test/utils/testing.go
Labels: component/testing, flaky test, kind/feature

#597 Support collecting cluster logs with kind.
  pkg/apis/kudo/v1alpha1/test_types.go
  pkg/kudoctl/cmd/test.go
  pkg/test/harness.go
Labels: component/testing, kind/feature

#595 Support installing a CRD in a test step and using it in a later test step.
  pkg/test/case.go
  pkg/test/case_test.go
  pkg/test/harness.go
  pkg/test/harness_integration_test.go
  pkg/test/step.go
  pkg/test/step_integration_test.go
  pkg/test/step_test.go
  pkg/test/test_data/crd-in-step/00-assert.yaml
  pkg/test/test_data/crd-in-step/00-crd.yaml
  pkg/test/test_data/crd-in-step/01-assert.yaml
  pkg/test/test_data/crd-in-step/01-create-mycrd.yaml
  pkg/test/test_data/list-pods/00-deployment.yaml
  pkg/test/test_data/list-pods/00-pod.yaml
  pkg/test/test_data/with-overrides/01-test-assert.yaml
  pkg/test/utils/kubernetes.go
  pkg/test/utils/kubernetes_test.go
Labels: component/testing, kind/enhancement

#605 Fix the default kind context to match kind's default.
  pkg/kudoctl/cmd/test.go
Labels: component/testing, kind/cleanup

#612 Do not Get after Create/Patch in plan execution controller
  pkg/controller/planexecution/planexecution_controller.go
Labels: component/operator, flaky test, kind/bug, priority/critical

#617 Do not apply label with version to fix upgrade issues
  pkg/controller/planexecution/planexecution_controller.go
  pkg/test/test_data/patch/00-assert.yaml
  pkg/test/test_data/patch/01-assert.yaml
Labels: backport

#616 Do not Get after Create/Patch in plan execution controller
  pkg/controller/planexecution/planexecution_controller.go
Labels: backport

#572 Support specifying many manifest directories to install in test harness.
  keps/0008-operator-testing.md
  pkg/apis/kudo/v1alpha1/test_types.go
  pkg/apis/kudo/v1alpha1/test_types_test.go
  pkg/kudoctl/cmd/test.go
  pkg/test/harness.go
Labels: component/testing, kind/feature

#610 Revert "Revert "Support installing a CRD in a test step and using it in a later test step.""
  pkg/test/case.go
  pkg/test/case_test.go
  pkg/test/harness.go
  pkg/test/harness_integration_test.go
  pkg/test/step.go
  pkg/test/step_integration_test.go
  pkg/test/step_test.go
  pkg/test/test_data/crd-in-step/00-assert.yaml
  pkg/test/test_data/crd-in-step/00-crd.yaml
  pkg/test/test_data/crd-in-step/01-assert.yaml
  pkg/test/test_data/crd-in-step/01-create-mycrd.yaml
  pkg/test/test_data/list-pods/00-deployment.yaml
  pkg/test/test_data/list-pods/00-pod.yaml
  pkg/test/test_data/with-overrides/01-test-assert.yaml
  pkg/test/utils/kubernetes.go
  pkg/test/utils/kubernetes_test.go
Labels: component/testing, kind/enhancement

#607 Fix InstallCRDs method to only install CRDs and ignore other resource types.
  pkg/test/harness.go
  pkg/test/utils/kubernetes.go
  pkg/test/utils/kubernetes_integration_test.go
Labels: component/testing, kind/bug

#638 Fix test harness deletion to be able to delete all resources in a namespace.
  docs/testing.md
  pkg/test/step.go
  pkg/test/test_data/delete-in-step/00-assert.yaml
  pkg/test/test_data/delete-in-step/00-create.yaml
  pkg/test/test_data/delete-in-step/01-assert.yaml
  pkg/test/test_data/delete-in-step/01-create.yaml
Labels: component/testing, kind/enhancement

#644 Replace manifests-dir and manifests-dirs with manifest-dir and ManifestsDirs and ManifestsDir with ManifestDirs.
  keps/0008-operator-testing.md
  kudo-test.yaml
  pkg/apis/kudo/v1alpha1/test_types.go
  pkg/apis/kudo/v1alpha1/test_types_test.go
  pkg/kudoctl/cmd/test.go
  pkg/test/harness.go
Labels: component/testing, kind/bug

#625 Proposal for E2E and CLI testing via test harness.
  keps/0004-add-testing-infrastructure.md
  keps/0008-operator-testing.md
Labels: component/testing, kind/kep

#585 Document Prow usage in KEP.
  keps/0004-add-testing-infrastructure.md
  keps/0014-pull-request-process.md
Labels: component/testing, kind/kep

#660 Fix labels after bad merge
  pkg/controller/planexecution/apply_conventions.go
Labels: release-blocker

#657 Do not requeue PlanExecution reconciliation if Instance does not exist.
  pkg/controller/planexecution/planexecution_controller.go
Labels: component/operator, kind/bug

#658 Fix leftover bug after renaming of labels
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: kind/bug

#663 Use DynamicRESTMapper to reload REST mappings when types are not found.
  pkg/test/test_data/crd-in-step/00-assert.yaml
  pkg/test/utils/dynamicrestmapper.go
  pkg/test/utils/kubernetes.go
Labels: component/testing, flaky test, kind/bug

#514 adding notes for installation via url
  docs/cli.md
Labels: hold

#516 Fix documentation after code changes
  docs/cli.md
Labels: hold

#661 Import auth providers to support GKE, etc.
  go.mod
  go.sum
  pkg/kudoctl/util/kudo/kudo.go
Labels: component/kudoctl, kind/bug, priority/critical

#667 Update OWNERS file.
  OWNERS
Labels: kind/cleanup, retest-not-required-docs-only, size/S

#666 Update event queue
  site/data/events/cloudnativecomputingswitzerland.yaml
  site/data/events/cloudnativeglasgow.yaml
  site/data/events/kubernetescolorado.yaml
  site/data/events/kubernetesfinland.yaml
Labels: approved, lgtm, size/S

#669 Drop arrows from short descriptions
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/cmd/test.go
  pkg/kudoctl/cmd/version.go
Labels: approved, kind/cleanup, lgtm, size/XS

#656 Implement CLI and E2E testing using the KUDO test harness.
  Makefile
  go.mod
  go.sum
  pkg/apis/kudo/v1alpha1/test_types.go
  pkg/apis/kudo/v1alpha1/zz_generated.deepcopy.go
  pkg/test/case.go
  pkg/test/case_test.go
  pkg/test/harness.go
  pkg/test/step.go
  pkg/test/test_data/cli-test/00-assert.yaml
  pkg/test/test_data/cli-test/00-create-pod.yaml
  pkg/test/test_data/cli-test/test_data/pod.yaml
  pkg/test/test_data/with-overrides/README.md
  pkg/test/utils/kubernetes.go
  pkg/test/utils/kubernetes_test.go
  test/integration/cli-install/00-assert.yaml
  test/integration/cli-install/00-install.yaml
  test/integration/cli-install/01-assert.yaml
  test/integration/cli-install/01-upgrade.yaml
  test/integration/cli-install/cli-install-operator/operator.yaml
  test/integration/cli-install/cli-install-operator/params.yaml
  test/integration/cli-install/cli-install-operator/templates/deployment.yaml
Labels: approved, component/testing, kind/feature, size/XL

#645 Add script for generating a krew plugin manifest.
  RELEASE.md
  hack/generate_krew.sh
Labels: approved, component/kudoctl, kind/enhancement, size/M

#643 Overhaul test harness documentation.
  docs/testing.md
  docs/testing/asserts.md
  docs/testing/reference.md
  docs/testing/steps.md
  docs/testing/test-environments.md
  docs/testing/tips.md
  site/config.yml
  site/layouts/docs/baseof.html
Labels: approved, component/testing, kind/documentation, size/XL

#671 Fix EXE path when generating Krew plugin.
  hack/generate_krew.sh
Labels: approved, kind/cleanup, lgtm, size/S

#670 Instance Controller: Refactored Create Operation
  go.mod
  go.sum
  pkg/controller/instance/instance_controller.go
  pkg/controller/planexecution/planexecution_controller.go
Labels: approved, kind/cleanup, lgtm, size/L

#659 Upgrade command
  config/samples/first-operator/templates/deployment.yaml
  go.mod
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/install/params.go
  pkg/kudoctl/cmd/install/params_test.go
  pkg/kudoctl/cmd/install_test.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/cmd/upgrade_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: approved, kind/feature, lgtm, size/XL
