Repository kudobuilder/kudo, pull requests merged in 2019-08, with the labels that each got.

#673 Update command
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/update_test.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: approved, kind/enhancement, size/L

#676 Add 0.4.0 blog post
  site/content/posts/announcing-kudo-0.4.0.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only, size/M

#678 Add contributing section to documentation
  docs/contributing.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only, size/M

#674 Add generated kubeconfigs and kubeconfig cache to gitignore.
  .gitignore
Labels: approved, kind/cleanup, lgtm, size/XS

#681 Upgrade integration test
  test/integration/upgrade-command/00-install.yaml
  test/integration/upgrade-command/01-assert.yaml
  test/integration/upgrade-command/01-upgrade.yaml
  test/integration/upgrade-command/first-operator/operator.yaml
  test/integration/upgrade-command/first-operator/params.yaml
  test/integration/upgrade-command/first-operator/templates/deployment.yaml
  test/integration/upgrade-command/second-operator/operator.yaml
  test/integration/upgrade-command/second-operator/params.yaml
  test/integration/upgrade-command/second-operator/templates/deployment.yaml
Labels: approved, kind/test, lgtm, size/L

#680 Kudo update integration test
  test/integration/update-command/00-install.yaml
  test/integration/update-command/01-assert.yaml
  test/integration/update-command/01-update.yaml
  test/integration/update-command/02-add-new-param.yaml
  test/integration/update-command/02-assert.yaml
  test/integration/update-command/03-assert.yaml
  test/integration/update-command/03-update-param-value.yaml
Labels: approved, kind/test, lgtm, size/M

#685 Consistent help messages for all commands
  pkg/kudoctl/cmd/get.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/cmd/version.go
Labels: approved, kind/cleanup, lgtm, size/S

#675 Backport Krew review feedback to generate_krew.sh
  hack/generate_krew.sh
Labels: approved, kind/cleanup, lgtm, size/S

#687 Remove SilenceUsage:true from all commands
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/cmd/version.go
Labels: approved, needs-kind, size/S

#686 Print out some messages in happy path of kudo upgrade
  pkg/kudoctl/cmd/upgrade.go
Labels: approved, needs-kind, size/XS

#651 Final phase of 'developing operators' docs
  docs/developing-operators.md
  docs/getting-started.md
Labels: approved, lgtm, retest-not-required-docs-only, size/M

#688 Unify feel of install, upgrade and update
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/update_test.go
  test/integration/update-command/01-update.yaml
  test/integration/update-command/02-add-new-param.yaml
  test/integration/update-command/03-update-param-value.yaml
Labels: approved, kind/cleanup, lgtm, size/M

#689 Get ready for 0.5.0
  docs/deployment/20-deployment.yaml
  docs/getting-started.md
Labels: approved, kind/documentation, lgtm, size/XS

#690 kafka: use kudo cli in the quickstart examples
  docs/examples/apache-kafka.md
  docs/examples/apache-zookeeper.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only, size/M

#695 Blogpost for 0.5.0
  site/content/posts/announcing-kudo-0.5.0.md
Labels: approved, kind/documentation, lgtm, retest-not-required-docs-only, size/S

#698 fix lingo in docs: task, not step
  docs/developing-operators.md
Labels: approved, kind/documentation, lgtm, needs-ok-to-test, retest-not-required-docs-only, size/XS

#697 Fix broken link to developing-operators
  docs/getting-started.md
Labels: approved, kind/documentation, needs-ok-to-test, retest-not-required-docs-only, size/XS

#699 Add Hamburg meetup
  site/data/events/cloudnativehamburg.yaml
Labels: approved, kind/documentation, lgtm, size/XS

#707 Fix flake in CreateOrUpdate
  pkg/test/utils/kubernetes.go
Labels: approved, kind/test, lgtm, size/XS

#706 Integration test for update plan
  test/integration/update-parameters/00-assert.yaml
  test/integration/update-parameters/00-install.yaml
  test/integration/update-parameters/01-assert.yaml
  test/integration/update-parameters/01-update-replicas-and-scale.yaml
  test/integration/update-parameters/02-assert.yaml
  test/integration/update-parameters/02-param-update.yaml
Labels: approved, kind/test, lgtm, size/S

#702 Upgrade plan test
  test/integration/upgrade-command/01-assert.yaml
  test/integration/upgrade-command/second-operator/operator.yaml
Labels: approved, kind/test, lgtm, size/S

#701 Add missing kind to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/cleanup, lgtm, retest-not-required-docs-only, size/XS

#704 update min minikube spec to allow zk/kafka
  docs/getting-started.md
Labels: approved, kind/documentation, lgtm, ok-to-test, retest-not-required-docs-only, size/XS

#700 Add update and upgrade docs
  docs/cli.md
Labels: approved, kind/documentation, retest-not-required-docs-only, size/S

#677 Bundle Feature: Create Package Bundle
  docs/cli.md
  go.mod
  pkg/kudoctl/bundle/bundle.go
  pkg/kudoctl/bundle/finder/bundle_finder.go
  pkg/kudoctl/bundle/package_test.go
  pkg/kudoctl/bundle/tar.go
  pkg/kudoctl/bundle/tar_test.go
  pkg/kudoctl/bundle/testdata/zk.tar.gz
  pkg/kudoctl/cmd/package.go
  pkg/kudoctl/cmd/package_test.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/files/file.go
Labels: approved, kind/feature, size/L

#708 Update date for K8s Finland Meetup, fix community link in announcements
  site/content/posts/announcing-kudo-0.2.0.md
  site/content/posts/announcing-kudo-0.3.0.md
  site/content/posts/announcing-kudo-0.4.0.md
  site/content/posts/announcing-kudo-0.5.0.md
  site/data/events/kubernetesfinland.yaml
Labels: approved, kind/documentation, lgtm, size/S

#705 Instance spec as part of plan execution CRD
  config/crds/kudo_v1alpha1_instance.yaml
  config/crds/kudo_v1alpha1_planexecution.yaml
  config/crds/kudo_v1alpha1_teststep.yaml
  config/crds/kudo_v1alpha1_testsuite.yaml
  hack/update_manifests.sh
  pkg/apis/kudo/v1alpha1/planexecution_types.go
  pkg/apis/kudo/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/planexecution/planexecution_controller.go
Labels: approved, kind/feature, lgtm, size/L

#715 Add Arkansas event
  site/data/events/kubernetesandcloudnativearkansas.yaml
Labels: approved, kind/documentation, needs-ok-to-test, size/XS

#694 Reduce the indirection by directly referencing controllers
  cmd/manager/main.go
  pkg/controller/add_instance.go
  pkg/controller/add_operator.go
  pkg/controller/add_operatorversion.go
  pkg/controller/add_planexecution.go
  pkg/controller/controller.go
  pkg/test/harness.go
Labels: approved, kind/cleanup, size/L

#709 Minor docs overhaul: wording, grammar, formatting
  docs/Comparison.md
  docs/cli.md
  docs/concepts.md
  docs/developing-operators.md
  docs/faq.md
  docs/getting-started.md
  keps/0000-kep-template.md
  keps/0002-dynamic-instances.md
  keps/0003-kep-cli.md
  keps/0004-add-testing-infrastructure.md
  keps/0005-cluster-resources-for-crds.md
  keps/0008-operator-testing.md
  keps/0009-operator-toolkit.md
  keps/0010-package-manager.md
  keps/0012-operator-extensions.md
  keps/0013-external-specs.md
  pkg/apis/kudo/v1alpha1/operatorversion_types.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_instance.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_operator.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_operatorversion.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/instance.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/operator.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/operatorversion.go
  pkg/client/informers/externalversions/kudo/v1alpha1/interface.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/operator/operator_controller.go
  pkg/controller/operatorversion/operatorversion_controller.go
  pkg/kudoctl/bundle/finder/bundle_finder.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/repo_index.go
  pkg/kudoctl/util/repo/repo_operator.go
  site/layouts/_default/baseof.html
Labels: approved, kind/documentation, size/L

#720 Add Nordics tour and San Diego
  site/data/events/cloudnativeaarhus.yaml
  site/data/events/cloudnativecopenhagen.yaml
  site/data/events/cloudnativestockholm.yaml
  site/data/events/sandiegocloudnativecomputingmeetup.yaml
Labels: approved, kind/documentation, needs-ok-to-test, size/S

#719 Add Phoenix date
  site/data/events/kubernetespheonix.yaml
Labels: approved, kind/documentation, needs-ok-to-test, size/XS

#716 Fix testing link
  docs/developing-operators.md
Labels: approved, kind/documentation, needs-ok-to-test, retest-not-required-docs-only, size/XS

#714 Fix getting started installation for 0.5.0
  docs/getting-started.md
Labels: approved, kind/documentation, retest-not-required-docs-only, size/XS

#724 Change date for Glasgow
  site/data/events/cloudnativeglasgow.yaml
Labels: approved, needs-kind, needs-ok-to-test, size/XS

#727 Fix some wording around the update subcommand
  docs/cli.md
  pkg/kudoctl/cmd/update.go
Labels: approved, kind/documentation, lgtm, size/S

#726 Add Tampa Kubernetes Meetup information
  site/data/events/cloudnativeaarhus.yaml
  site/data/events/cloudnativecopenhagen.yaml
  site/data/events/cloudnativestockholm.yaml
  site/data/events/kubernetestampa.yml
Labels: approved, kind/documentation, lgtm, size/S

#732 add Data Natives Vienna meetup information
  site/data/events/datanativesvienna.yaml
Labels: approved, kind/documentation, lgtm, size/XS

#735 Generated Files Fix
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_instance.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_operator.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/fake/fake_operatorversion.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/instance.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/operator.go
  pkg/client/clientset/versioned/typed/kudo/v1alpha1/operatorversion.go
  pkg/client/informers/externalversions/kudo/v1alpha1/interface.go
Labels: approved, kind/cleanup, kind/infrastructure, lgtm, size/M

#722 Fix race with ActivePlan between Instance and PlanExecution controllers
  pkg/controller/instance/instance_controller.go
  pkg/controller/planexecution/planexecution_controller.go
Labels: approved, kind/bug, size/L

#654 KEP: Draft For Repository (targeted for KEP-15)
  keps/0015-repository-management.md
Labels: approved, retest-not-required-docs-only, size/L

#736 KUDO Init
  pkg/kudoctl/cmd/get/get.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init/crds.go
  pkg/kudoctl/cmd/init/manager.go
  pkg/kudoctl/cmd/init/prereqs.go
  pkg/kudoctl/cmd/init/wait.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/kube/config.go
  pkg/kudoctl/kube/pod.go
  pkg/test/utils/kubernetes.go
  pkg/version/version.go
Labels: approved, kind/feature, size/XXL
