Repository kudobuilder/kudo, pull requests merged in 2020-04, with the labels that each got.

#1455 Package Verify Support for Template Range
  pkg/kudoctl/packages/verifier/template/parser.go
  pkg/kudoctl/packages/verifier/template/verify_parameters_test.go
Labels: release/highlight

#1460 Package Verify of Versions
  pkg/kudoctl/cmd/testdata/invalid-params.golden
  pkg/kudoctl/cmd/verify/verify.go
  pkg/kudoctl/cmd/verify/verify_test.go
Labels: release/highlight

#1462 Man's Search for Operators
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/search.go
  pkg/kudoctl/cmd/search_test.go
  pkg/kudoctl/cmd/testdata/index.yaml
  pkg/kudoctl/cmd/testdata/merge-index.yaml.golden
  pkg/kudoctl/cmd/testdata/search1.golden
  pkg/kudoctl/cmd/testdata/search2.golden
  pkg/kudoctl/cmd/testdata/search3.golden
  pkg/kudoctl/util/repo/repo_operator.go
  pkg/kudoctl/util/repo/resolver_repo.go
  pkg/kudoctl/util/repo/resolver_repo_test.go
Labels: release/highlight

#1461 Waiting For a Plan to Finish
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/plan/plan_status.go
  pkg/kudoctl/cmd/plan/plan_wait.go
  pkg/kudoctl/util/kudo/install.go
  pkg/kudoctl/util/kudo/install_test.go
  pkg/kudoctl/util/kudo/kudo.go
Labels: release/highlight

#1456 Update third-party dependencies and use Go 1.14
  .circleci/config.yml
  Dispatchfile.cue
  Dockerfile
  build/Dockerfile
  build/test-images.sh
  go.mod
  go.sum
  test/Dockerfile
Labels: component/tooling

#1310 KEP-22: Add initial design on diagnostics bundles
  keps/0022-diagnostics-bundle.md
  keps/README.md
Labels: kep/22, kind/kep

#1484 Add possibility for pipe-tasks to pipe env-files
  config/crds/kudo.dev_operatorversions.yaml
  pkg/apis/kudo/v1beta1/operatorversion_types.go
  pkg/engine/task/env_file.go
  pkg/engine/task/task.go
  pkg/engine/task/task_pipe.go
  pkg/engine/task/task_pipe_test.go
  pkg/engine/task/task_test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
Labels: release/highlight

#1474 Remove redundant `Instance.Status.AggregatedStatus` field
  config/crds/kudo.dev_instances.yaml
  pkg/apis/kudo/v1beta1/instance_types.go
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/apis/kudo/v1beta1/instance_types_helpers_test.go
  pkg/apis/kudo/v1beta1/zz_generated.deepcopy.go
  pkg/controller/instance/instance_controller.go
  pkg/engine/health/health.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
  test/e2e/cli-install-uninstall/01-assert.yaml
  test/e2e/terminal-failed-job/01-assert.yaml
  test/e2e/terminal-failed-job/02-assert.yaml
  test/e2e/toggle-task/01-assert.yaml
  test/e2e/toggle-task/02-assert.yaml
  test/integration/cli-install/00-assert.yaml
  test/integration/cli-install/01-assert.yaml
  test/integration/create-operator-in-operator/01-assert.yaml
  test/integration/immutable-client-ip/00-assert.yaml
  test/integration/immutable-client-ip/01-assert.yaml
  test/integration/install-existing-crds-in-operator/00-assert.yaml
  test/integration/instance-controller-param-change-custom-trigger/00-assert.yaml
  test/integration/instance-controller-param-change-custom-trigger/01-assert.yaml
  test/integration/instance-controller-param-change-fallback-to-deploy/00-assert.yaml
  test/integration/instance-controller-param-change-fallback-to-deploy/01-assert.yaml
  test/integration/instance-controller-param-change-no-trigger/00-assert.yaml
  test/integration/instance-controller-param-change-no-trigger/01-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-deploy/00-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-deploy/01-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-update/00-assert.yaml
  test/integration/instance-controller-upgrade-fallback-to-update/01-assert.yaml
  test/integration/instance-controller-upgrade/00-assert.yaml
  test/integration/instance-controller-upgrade/01-assert.yaml
  test/integration/operator-with-custom-crd/01-assert.yaml
  test/integration/parameter-types-operator/01-assert.yaml
  test/integration/parameter-types/01-assert.yaml
  test/integration/parse-param-operator-in-operator/01-assert.yaml
  test/integration/racy-reconcile/01-assert.yaml
  test/integration/rendering-error-plan-failed/00-assert.yaml
  test/integration/step-delete/00-assert.yaml
  test/integration/step-delete/01-assert.yaml
  test/integration/update-parameters/00-assert.yaml
  test/integration/update-parameters/01-assert.yaml
  test/integration/update-parameters/02-assert.yaml
  test/integration/upgrade-command/00-assert.yaml
  test/integration/upgrade-command/01-assert.yaml
Labels: release/breaking-change
