Repository kudobuilder/kudo, pull requests merged in 2020-06, with the labels that each got.

#1546 Detect different versions of cert-manager
  pkg/engine/health/health.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/repo_add_test.go
  pkg/kudoctl/cmd/repo_context_test.go
  pkg/kudoctl/cmd/repo_list_test.go
  pkg/kudoctl/cmd/repo_remove_test.go
  pkg/kudoctl/cmd/root.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/kudoinit/prereq/webhook_test.go
  pkg/kudoctl/kudoinit/setup/setup.go
Labels: release/blocker

#1290 Add test cases for apis.
  pkg/apis/kudo/v1beta1/instance_types_helpers_test.go
Labels: license/needs-dco

#1537 Bump Kubernetes dependencies to 1.18.3
  config/crds/kudo.dev_instances.yaml
  config/crds/kudo.dev_operators.yaml
  config/crds/kudo.dev_operatorversions.yaml
  go.mod
  go.sum
  hack/update_codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/kudo/v1beta1/fake/fake_instance.go
  pkg/client/clientset/versioned/typed/kudo/v1beta1/fake/fake_operator.go
  pkg/client/clientset/versioned/typed/kudo/v1beta1/fake/fake_operatorversion.go
  pkg/client/clientset/versioned/typed/kudo/v1beta1/instance.go
  pkg/client/clientset/versioned/typed/kudo/v1beta1/operator.go
  pkg/client/clientset/versioned/typed/kudo/v1beta1/operatorversion.go
  pkg/client/informers/externalversions/kudo/v1beta1/instance.go
  pkg/client/informers/externalversions/kudo/v1beta1/operator.go
  pkg/client/informers/externalversions/kudo/v1beta1/operatorversion.go
  pkg/kudoctl/cmd/diagnostics/resource_funcs.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
  pkg/kudoctl/kudoinit/crd/crds.go
  pkg/kudoctl/kudoinit/manager/manager.go
  pkg/kudoctl/kudoinit/prereq/namespace.go
  pkg/kudoctl/kudoinit/prereq/serviceaccount.go
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/kudoinit/setup/wait.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
Labels: do-not-merge/hold
