Repository kudobuilder/kudo, pull requests merged in 2020-05, with the labels that each got.

#1483 KEP-27: Detailed pod restart control by dependencies hash
  go.mod
  pkg/controller/instance/instance_controller.go
  pkg/engine/renderer/dependencies.go
  pkg/engine/renderer/dependencies_test.go
  pkg/engine/renderer/enhancer.go
  pkg/engine/renderer/enhancer_test.go
  pkg/engine/workflow/engine.go
  pkg/engine/workflow/engine_test.go
  pkg/test/fake/client.go
  pkg/util/kudo/labels.go
  test/e2e/dependencies-hash/00-assert.yaml
  test/e2e/dependencies-hash/01-assert.yaml
  test/e2e/dependencies-hash/01-install.yaml
  test/e2e/dependencies-hash/02-assert.yaml
  test/e2e/dependencies-hash/02-update-replicas.yaml
  test/e2e/dependencies-hash/03-assert.yaml
  test/e2e/dependencies-hash/03-update-param.yaml
  test/e2e/dependencies-hash/04-assert.yaml
  test/e2e/dependencies-hash/04-update-replicas-again.yaml
  test/e2e/dependencies-hash/05-assert.yaml
  test/e2e/dependencies-hash/06-assert.yaml
  test/e2e/dependencies-hash/06-update-param-and-replica.yaml
  test/e2e/dependencies-hash/dep-operator/operator.yaml
  test/e2e/dependencies-hash/dep-operator/params.yaml
  test/e2e/dependencies-hash/dep-operator/templates/configmap.yaml
  test/e2e/dependencies-hash/dep-operator/templates/deployment.yaml
Labels: release/highlight

#1531 KEP-31: Impl of `--create-namespace`
  config/crds/kudo.dev_operators.yaml
  pkg/apis/kudo/v1beta1/operator_types.go
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
  pkg/kudoctl/packages/convert/resources.go
  pkg/kudoctl/packages/types.go
  pkg/kudoctl/util/kudo/install.go
  pkg/kudoctl/util/kudo/install_test.go
  pkg/kudoctl/util/kudo/kudo.go
Labels: release/highlight

#1497 Removed `--webhook` option
  Makefile
  cmd/manager/main.go
  go.mod
  hack/run-e2e-tests.sh
  kudo-e2e-test.yaml.tmpl
  kudo-test.yaml
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
  pkg/kudoctl/cmd/init.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/manager/manager.go
  pkg/kudoctl/kudoinit/options.go
  pkg/kudoctl/kudoinit/prereq/namespace_test.go
  pkg/kudoctl/kudoinit/prereq/serviceaccount_test.go
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/kudoinit/prereq/webhook_test.go
  pkg/kudoctl/util/kudo/upgrade.go
  test/README.md
  test/cert/ca.crt
  test/cert/tls.crt
  test/cert/tls.key
  test/integration/immutable-client-ip/00-install-instance.yaml
  test/integration/immutable-client-ip/01-update-parameter.yaml
  test/integration/racy-reconcile/00-install-instance.yaml
  test/integration/racy-reconcile/01-install-operatorversion.yaml
  test/integration/update-command/00-install.yaml
  test/integration/update-command/01-assert.yaml
  test/integration/update-command/01-update.yaml
  test/integration/update-command/02-add-new-param.yaml
  test/integration/update-command/02-assert.yaml
  test/integration/update-command/02-update.yaml
  test/integration/update-command/03-update-param-value.yaml
  test/integration/update-parameters/00-assert.yaml
  test/integration/update-parameters/00-install.yaml
  test/integration/update-parameters/01-assert.yaml
  test/integration/update-parameters/01-update-replicas-and-scale.yaml
  test/integration/update-parameters/01-update.yaml
  test/integration/update-parameters/02-assert.yaml
  test/integration/update-parameters/02-param-update.yaml
  test/integration/update-parameters/02-update.yaml
  test/manifests/instance-admission-webhook.yaml
  test/manifests/toy-operator.yaml
Labels: release/breaking-change

#1536 Namespace Package Verify
  pkg/kudoctl/cmd/verify/verify.go
  pkg/kudoctl/packages/verifier/template/verify_namespace.go
  pkg/kudoctl/packages/verifier/template/verify_namespace_test.go
  pkg/kudoctl/packages/verifier/template/verify_references.go
Labels: release/breaking-change, release/highlight

#1470 Plan Update and Trigger with Wait
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/cmd/plan/plan_trigger.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
  pkg/kudoctl/util/kudo/upgrade.go
Labels: release/highlight
