Repository kudobuilder/kudo, pull requests merged in 2020-02, with the labels that each got.

#1325 Simplified and updated go.mod
  go.mod
  go.sum
Labels: dependencies, size/S

#1168 Add a pre-commit hook to check for signed-off commits
  .pre-commit-config.yaml
  hack/check-commit-signed-off.sh
Labels: component/linter

#1358 Explicitly cover only specific plan status for cleanup plans
  pkg/controller/instance/instance_controller.go
Labels: kind/bug

#1332 Fix `ApplyTask` patch behavior
  pkg/engine/task/task_apply.go
  pkg/engine/task/task_delete.go
  pkg/engine/task/task_pipe.go
  pkg/util/kudo/labels.go
  test/integration/remove-pod-container/00-assert.yaml
  test/integration/remove-pod-container/00-errors.yaml
  test/integration/remove-pod-container/00-install.yaml
  test/integration/remove-pod-container/01-assert.yaml
  test/integration/remove-pod-container/01-update.yaml
  test/integration/remove-pod-container/02-assert.yaml
  test/integration/remove-pod-container/02-errors.yaml
  test/integration/remove-pod-container/02-update_param.yaml
  test/integration/remove-pod-container/dual-pod-operator/operator.yaml
  test/integration/remove-pod-container/dual-pod-operator/params.yaml
  test/integration/remove-pod-container/dual-pod-operator/templates/deployment.yaml
Labels: needs review, release/breaking-change

#1186 Verify that cert manager is installed
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/verify/verify.go
  pkg/kudoctl/kudoinit/crd/crds.go
  pkg/kudoctl/kudoinit/manager/manager.go
  pkg/kudoctl/kudoinit/prereq/namespace.go
  pkg/kudoctl/kudoinit/prereq/namespace_test.go
  pkg/kudoctl/kudoinit/prereq/prereqs.go
  pkg/kudoctl/kudoinit/prereq/prereqs_test.go
  pkg/kudoctl/kudoinit/prereq/serviceaccount.go
  pkg/kudoctl/kudoinit/prereq/serviceaccount_test.go
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/kudoinit/prereq/webhook_test.go
  pkg/kudoctl/kudoinit/setup/setup.go
  pkg/kudoctl/kudoinit/types.go
  pkg/kudoctl/packages/verifier.go
  pkg/kudoctl/packages/verifier/plan/verify_references.go
  pkg/kudoctl/packages/verifier/task/verify_build.go
  pkg/kudoctl/packages/verifier/task/verify_references.go
  pkg/kudoctl/packages/verifier/template/verify_parameters.go
  pkg/kudoctl/packages/verifier/template/verify_references.go
  pkg/kudoctl/packages/verifier/template/verify_render.go
  pkg/kudoctl/packages/verifier/types.go
  pkg/kudoctl/verifier/result.go
Labels: needs review

#1368 Remove the Instance finalizer only if the `cleanup` plan was successfully finished
  pkg/controller/instance/instance_controller.go
Labels: kind/bug

#1365 Change LastFinished to LastUpdated, timestamp every plan status change
  config/crds/kudo.dev_instances.yaml
  pkg/apis/kudo/v1beta1/instance_types.go
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/apis/kudo/v1beta1/instance_types_helpers_test.go
  pkg/apis/kudo/v1beta1/zz_generated.deepcopy.go
  pkg/controller/instance/instance_controller.go
  pkg/engine/workflow/engine.go
  pkg/engine/workflow/engine_test.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/plan/plan_status.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
Labels: release/breaking-change
