Repository kudobuilder/kudo, pull requests merged in 2020-07, with the labels that each got.

#1579 Installing Local Operators Requires Abs or relative notation
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/packages/resolver/resolver.go
Labels: release/breaking-change, release/highlight

#1582 Generate KUDO Manifests
  .gitignore
  Makefile
  hack/deploy-dev-prereqs.sh
  hack/update-manifests.sh
  hack/update-webhook-config.sh
Labels: release/highlight

#1574 KEP-32: Community Repository Management
  keps/0032-community-repository-management.md
Labels: kep/32

#1575 Implementation of KEP-30: Immutable Parameters
  config/crds/kudo.dev_operatorversions.yaml
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/apis/kudo/v1beta1/operatorversion_types.go
  pkg/apis/kudo/v1beta1/parameter_types.go
  pkg/apis/kudo/v1beta1/parameter_types_helpers.go
  pkg/apis/kudo/v1beta1/parameter_types_helpers_test.go
  pkg/apis/kudo/v1beta1/zz_generated.deepcopy.go
  pkg/kudoctl/cmd/generate/testdata/parameter.golden
  pkg/kudoctl/cmd/package_list_params.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/cmd/testdata/params-list.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
  pkg/kudoctl/packages/convert/parameters.go
  pkg/kudoctl/packages/install/package.go
  pkg/kudoctl/packages/install/package_test.go
  pkg/kudoctl/packages/reader/parser.go
  pkg/kudoctl/packages/testdata/zk-crd-golden1/operatorversion.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/operatorversion.golden
  pkg/kudoctl/packages/types.go
  pkg/kudoctl/packages/verifier/template/verify_parameters.go
  pkg/kudoctl/packages/verifier/template/verify_parameters_test.go
  pkg/webhook/instance_admission.go
  pkg/webhook/instance_admission_test.go
  test/e2e/immutable-parameter/00-assert.yaml
  test/e2e/immutable-parameter/00-install.yaml
  test/e2e/immutable-parameter/01-assert.yaml
  test/e2e/immutable-parameter/01-fail-to-update-param.yaml
  test/e2e/immutable-parameter/immutable-param/operator.yaml
  test/e2e/immutable-parameter/immutable-param/params.yaml
  test/e2e/immutable-parameter/immutable-param/templates/deployment.yaml
Labels: release/highlight

#1615 Chore: Update third-party dependencies to their latest releases
  .golangci.yml
  Makefile
  config/crds/kudo.dev_instances.yaml
  config/crds/kudo.dev_operators.yaml
  config/crds/kudo.dev_operatorversions.yaml
  go.mod
  go.sum
  hack/install-golangcilint.sh
  pkg/engine/renderer/dependencies_test.go
  pkg/engine/renderer/enhancer_test.go
  pkg/engine/task/podexec/pod_exec.go
  pkg/engine/task/task_delete.go
  pkg/engine/task/task_kudo_operator_test.go
  pkg/kudoctl/cmd/generate/maintainer_test.go
  pkg/kudoctl/cmd/generate/parameter_test.go
  pkg/kudoctl/cmd/generate/plans_test.go
  pkg/kudoctl/cmd/generate/task_test.go
  pkg/kudoctl/cmd/get/get_test.go
  pkg/kudoctl/cmd/init_integration_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/install/install_test.go
  pkg/kudoctl/cmd/package_list_params_test.go
  pkg/kudoctl/cmd/package_list_plans_test.go
  pkg/kudoctl/cmd/package_list_tasks_test.go
  pkg/kudoctl/cmd/package_new_test.go
  pkg/kudoctl/cmd/package_verify_test.go
  pkg/kudoctl/cmd/prompt/operator.go
  pkg/kudoctl/cmd/repo_add_test.go
  pkg/kudoctl/cmd/repo_index_test.go
  pkg/kudoctl/cmd/repo_list_test.go
  pkg/kudoctl/cmd/search_test.go
  pkg/kudoctl/cmd/test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/cmd/update_test.go
  pkg/kudoctl/cmd/upgrade_test.go
  pkg/kudoctl/kudoinit/crd/bindata.go
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/packages/install/namespace_test.go
  pkg/kudoctl/packages/reader/reader_test.go
  pkg/kudoctl/packages/verifier/template/parser_test.go
  pkg/kudoctl/packages/writer/writer_test.go
  pkg/kudoctl/resources/upgrade/operatorversion.go
  pkg/kudoctl/util/kudo/kudo_test.go
  pkg/kudoctl/util/repo/index.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/version/version.go
  tools.go
Labels: component/linter, component/testing, dependencies

#1622 Update the default community repository URL
  pkg/kudoctl/cmd/testdata/repo-list.golden
  pkg/kudoctl/cmd/testdata/skip-check-add-list.golden
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/testdata/repositories.yaml.golden
Labels: community, kep/32, release/breaking-change
