Repository kudobuilder/kudo, pull requests merged in 2020-10, with the labels that each got.

#1685 Bump direct dependencies to their latest releases
  .circleci/config.yml
  Dispatchfile
  Dockerfile
  Makefile
  build/Dockerfile
  build/test-images.sh
  config/crds/kudo.dev_instances.yaml
  config/crds/kudo.dev_operators.yaml
  config/crds/kudo.dev_operatorversions.yaml
  go.mod
  go.sum
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/listers/kudo/v1beta1/instance.go
  pkg/client/listers/kudo/v1beta1/operator.go
  pkg/client/listers/kudo/v1beta1/operatorversion.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.json.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
  test/Dockerfile
Labels: dependencies

#1707 Calculate health for services
  pkg/kubernetes/status/health.go
  pkg/kubernetes/status/health_test.go
Labels: kind/enhancement

#1706 Implement Ready condition for Instance type
  config/crds/kudo.dev_instances.yaml
  pkg/apis/kudo/v1beta1/instance_types.go
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/apis/kudo/v1beta1/zz_generated.deepcopy.go
  pkg/controller/instance/instance_controller.go
  pkg/kubernetes/status/readiness.go
  pkg/kubernetes/status/readiness_test.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.json.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/kudoinit/crd/bindata.go
  test/e2e/readiness/00-assert.yaml
  test/e2e/readiness/00-install.yaml
  test/e2e/readiness/01-assert.yaml
  test/e2e/readiness/01-updatedeployment.yaml
  test/e2e/readiness/first-operator/operator.yaml
  test/e2e/readiness/first-operator/params.yaml
  test/e2e/readiness/first-operator/templates/deployment.yaml
Labels: release/blocker

#1684 Rename OperatorVersion CRs from `name-<operatorVersion>` to `name-<appVersion>-<operatorVersion>`
  go.sum
  hack/run-operator-tests.sh
  pkg/apis/kudo/v1beta1/operatorversion_types_helpers.go
  pkg/controller/instance/resolver_incluster.go
  pkg/engine/task/task_kudo_operator.go
  pkg/kudoctl/cmd/verify/verify.go
  pkg/kudoctl/kube/config.go
  pkg/kudoctl/kudoinit/migration/migration.go
  pkg/kudoctl/kudoinit/migration/migration_helper.go
  pkg/kudoctl/kudoinit/setup/setup.go
  pkg/kudoctl/packages/convert/resources.go
  pkg/kudoctl/packages/resolver/resolver_incluster.go
  pkg/kudoctl/packages/resolver/resolver_incluster_test.go
  pkg/kudoctl/packages/testdata/zk-crd-golden1/instance.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden1/operatorversion.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/instance.golden
  pkg/kudoctl/packages/testdata/zk-crd-golden2/operatorversion.golden
  pkg/kudoctl/packages/types.go
  pkg/kudoctl/resources/dependencies/resolve.go
  pkg/kudoctl/resources/dependencies/resolve_test.go
  pkg/kudoctl/util/repo/resolver_repo.go
  pkg/util/kudo/versions.go
  pkg/util/kudo/versions_test.go
  test/e2e/apply-delete-apply/00-assert.yaml
  test/e2e/plan-trigger/00-assert.yaml
  test/e2e/plan-trigger/01-assert.yaml
  test/e2e/terminal-failed-job/00-assert.yaml
  test/e2e/terminal-failed-job/01-assert.yaml
  test/e2e/toggle-task/00-assert.yaml
  test/e2e/toggle-task/01-assert.yaml
  test/integration/invalid-crd-install/00-assert.yaml
  test/upgrade/upgrade-to-current/01-assert.yaml
  test/upgrade/upgrade-to-current/02-assert.yaml
  test/upgrade/upgrade-to-current/03-assert.yaml
  test/upgrade/upgrade-to-current/simple-op-0.1.0/operator.yaml
  test/upgrade/upgrade-to-current/simple-op-0.2.0/operator.yaml
Labels: release/blocker, release/breaking-change
