Repository kudobuilder/kudo, pull requests merged in 2020-01, with the labels that each got.

#1222 Operator Skeleton Generators
  pkg/apis/kudo/v1beta1/operatorversion_types.go
  pkg/kudoctl/cmd/generate/maintainer.go
  pkg/kudoctl/cmd/generate/maintainer_test.go
  pkg/kudoctl/cmd/generate/operator.go
  pkg/kudoctl/cmd/generate/operator_test.go
  pkg/kudoctl/cmd/generate/parameter.go
  pkg/kudoctl/cmd/generate/parameter_test.go
  pkg/kudoctl/cmd/generate/plans.go
  pkg/kudoctl/cmd/generate/plans_test.go
  pkg/kudoctl/cmd/generate/task.go
  pkg/kudoctl/cmd/generate/task_test.go
  pkg/kudoctl/cmd/generate/testdata/maintainer.golden
  pkg/kudoctl/cmd/generate/testdata/parameter.golden
  pkg/kudoctl/cmd/generate/testdata/plan.golden
  pkg/kudoctl/cmd/generate/testdata/task.golden
  pkg/kudoctl/cmd/package.go
  pkg/kudoctl/cmd/package_add.go
  pkg/kudoctl/cmd/package_add_maintainer.go
  pkg/kudoctl/cmd/package_add_parameter.go
  pkg/kudoctl/cmd/package_add_plan.go
  pkg/kudoctl/cmd/package_add_task.go
  pkg/kudoctl/cmd/package_new.go
  pkg/kudoctl/cmd/package_params_list.go
  pkg/kudoctl/cmd/prompt/operator.go
  pkg/kudoctl/cmd/prompt/prompt.go
  pkg/kudoctl/packages/resolver/resolver_local.go
  pkg/kudoctl/util/repo/resolver_repo.go
Labels: needs review

#1223 Package List (Parameters | Tasks | Plans)
  pkg/kudoctl/cmd/package.go
  pkg/kudoctl/cmd/package_list.go
  pkg/kudoctl/cmd/package_list_params.go
  pkg/kudoctl/cmd/package_list_params_test.go
  pkg/kudoctl/cmd/package_list_plans.go
  pkg/kudoctl/cmd/package_list_plans_test.go
  pkg/kudoctl/cmd/package_list_tasks.go
  pkg/kudoctl/cmd/package_list_tasks_test.go
  pkg/kudoctl/cmd/package_params.go
  pkg/kudoctl/cmd/testdata/plans-list.golden
  pkg/kudoctl/cmd/testdata/plans-with-tasks-list.golden
  pkg/kudoctl/cmd/testdata/tasks-list.golden
Labels: needs review, release-highlight

#1243 Run a KUDO deployment for E2E testing
  Dockerfile
  Makefile
  hack/run-e2e-tests.sh
  kudo-e2e-test.yaml.tmpl
  test/Dockerfile
Labels: component/testing, needs review

#1028 KEP-19: Versioning for operator packages
  keps/0019-package-api-versioning.md
  keps/README.md
Labels: kep/19, kind/kep

#1254 Refactor Instance Methods Try 2
  pkg/apis/kudo/v1beta1/instance_types.go
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/apis/kudo/v1beta1/instance_types_test.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
Labels: epic/upgrade-kudo

#1257 Implement KEP-19 by distinguishing between app and operator version
  pkg/kudoctl/cmd/generate/operator_test.go
  pkg/kudoctl/cmd/generate/testdata/maintainer.golden
  pkg/kudoctl/cmd/generate/testdata/plan.golden
  pkg/kudoctl/cmd/generate/testdata/task.golden
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/cmd/package_list.go
  pkg/kudoctl/cmd/package_list_params.go
  pkg/kudoctl/cmd/package_list_plans.go
  pkg/kudoctl/cmd/package_list_tasks.go
  pkg/kudoctl/cmd/package_new.go
  pkg/kudoctl/cmd/prompt/operator.go
  pkg/kudoctl/cmd/repo_index_test.go
  pkg/kudoctl/cmd/testdata/index.yaml
  pkg/kudoctl/cmd/testdata/index.yaml.golden
  pkg/kudoctl/cmd/testdata/merge-index.yaml.golden
  pkg/kudoctl/cmd/testdata/merge.yaml
  pkg/kudoctl/cmd/testdata/newop/operator.yaml.golden
  pkg/kudoctl/cmd/testdata/repo-list.golden
  pkg/kudoctl/cmd/testdata/skip-check-add-list.golden
  pkg/kudoctl/cmd/upgrade.go
  pkg/kudoctl/packages/package.go
  pkg/kudoctl/packages/resolver/resolver.go
  pkg/kudoctl/packages/resolver/resolver_local.go
  pkg/kudoctl/packages/resolver/resolver_local_test.go
  pkg/kudoctl/packages/resolver/resolver_test.go
  pkg/kudoctl/packages/resolver/resolver_url.go
  pkg/kudoctl/packages/testdata/zk.tgz
  pkg/kudoctl/packages/testdata/zk/operator.yaml
  pkg/kudoctl/packages/types.go
  pkg/kudoctl/packages/writer/writer_tar.go
  pkg/kudoctl/packages/writer/writer_test.go
  pkg/kudoctl/util/repo/index.go
  pkg/kudoctl/util/repo/index_test.go
  pkg/kudoctl/util/repo/repo.go
  pkg/kudoctl/util/repo/resolver_repo.go
  pkg/kudoctl/util/repo/testdata/flink-index.yaml.golden
  pkg/kudoctl/util/repo/testdata/repositories.yaml.golden
  test/e2e/cli-install-uninstall/first-operator/operator.yaml
  test/integration/cli-install/cli-install-operator/operator.yaml
  test/integration/first-operator-test/first-operator/operator.yaml
  test/integration/install-existing-crds-in-operator/crd-operator/operator.yaml
  test/integration/operator-with-custom-crd/operator/operator.yaml
  test/integration/upgrade-command/first-operator/operator.yaml
  test/integration/upgrade-command/second-operator/operator.yaml
Labels: kep/19

#1264 Forces pulling down base image before building new image via goreleaser
  .goreleaser.yml
Labels: ci, component/controller, kind/infrastructure

#911 Add feature gate scaffold
  go.mod
  pkg/feature/doc.go
  pkg/feature/feature.go
Labels: hold

#1299 Enable the 'scopelint' and 'unconvert' linters
  .golangci.yml
  pkg/engine/renderer/enhancer.go
  pkg/engine/task/task_pipe_test.go
  pkg/engine/task/task_test.go
  pkg/kudoctl/cmd/init_test.go
  pkg/kudoctl/cmd/repo_index_test.go
  pkg/kudoctl/env/environment_test.go
  pkg/kudoctl/http/http_client_test.go
  pkg/kudoctl/kudoinit/setup/wait.go
  pkg/kudoctl/packages/reader/reader_test.go
  pkg/test/case_test.go
  pkg/test/harness.go
  pkg/test/step.go
  pkg/test/step_test.go
  pkg/test/utils/kubernetes_test.go
  pkg/version/version_test.go
Labels: component/linter

#1250 Store KinD logs artifact in E2E tests
  .circleci/config.yml
  test/run_tests.sh
Labels: component/testing

#1308 Apply metadata the same way as Kustomize did
  pkg/engine/renderer/enhancer.go
  pkg/engine/renderer/enhancer_test.go
Labels: needs review

#1317 KEP-23: Enabling and disabling features in operators
  keps/0023-enable-disable-features.md
  keps/README.md
Labels: kep/23
