Repository kudobuilder/kudo, pull requests merged in 2020-03, with the labels that each got.

#1356 KEP-24: Enhanced Operator Parameters
  keps/0024-parameter-enhancement.md
Labels: kep/24, kind/kep

#1375 KEP-25: Implementation of toYaml function.
  pkg/engine/renderer/engine.go
  pkg/engine/renderer/engine_test.go
  pkg/engine/renderer/functions.go
Labels: kep/25

#1382 Mark KEP-25 as implemented and refresh list.
  keps/0025-template-to-yaml-function.md
  keps/README.md
Labels: kep/25

#1371 Sort output of plan status and history commands
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/plan/plan_status.go
  pkg/kudoctl/cmd/plan/plan_status_test.go
Labels: component/cli

#1376 Support typed parameter values
  config/crds/kudo.dev_operatorversions.yaml
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/apis/kudo/v1beta1/operatorversion_types.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
  pkg/engine/task/task.go
  pkg/engine/task/task_toggle.go
  pkg/engine/task/task_toggle_test.go
  pkg/engine/workflow/engine.go
  pkg/kudoctl/cmd/generate/operator.go
  pkg/kudoctl/cmd/generate/operator_test.go
  pkg/kudoctl/cmd/generate/parameter.go
  pkg/kudoctl/cmd/generate/parameter_test.go
  pkg/kudoctl/cmd/package_list_params.go
  pkg/kudoctl/cmd/prompt/operator.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/cmd/verify/verify.go
  pkg/kudoctl/cmd/verify/verify_test.go
  pkg/kudoctl/kudoinit/crd/bindata.go
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/packages/convert/parameters.go
  pkg/kudoctl/packages/convert/resources.go
  pkg/kudoctl/packages/reader/read_dir.go
  pkg/kudoctl/packages/reader/reader_tar.go
  pkg/kudoctl/packages/reader/reader_test.go
  pkg/kudoctl/packages/resolver/resolver_url.go
  pkg/kudoctl/packages/types.go
  pkg/kudoctl/packages/verifier/plan/verify_references_test.go
  pkg/kudoctl/packages/verifier/template/verify_parameters.go
  pkg/kudoctl/packages/verifier/template/verify_parameters_test.go
  pkg/kudoctl/packages/verifier/template/verify_references_test.go
  pkg/kudoctl/packages/verifier/template/verify_render.go
  pkg/kudoctl/packages/verifier/template/verify_render_test.go
  pkg/kudoctl/util/kudo/install_test.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
  pkg/kudoctl/util/kudo/upgrade.go
  pkg/kudoctl/util/repo/resolver_repo.go
  pkg/kudoctl/verifier/result.go
  pkg/util/convert/convert.go
  pkg/util/convert/convert_test.go
  pkg/util/kudo/convert_types.go
  pkg/webhook/instance_admission_test.go
  test/e2e/cli-install-uninstall/first-operator/params.yaml
  test/e2e/cli-install-uninstall/first-operator/templates/deployment.yaml
  test/integration/parameter-types-operator/01-assert.yaml
  test/integration/parameter-types-operator/01-install.yaml
  test/integration/parameter-types-operator/operator/operator.yaml
  test/integration/parameter-types-operator/operator/params.yaml
  test/integration/parameter-types-operator/operator/templates/deployment.yaml
  test/integration/parameter-types/01-assert.yaml
  test/integration/parameter-types/01-install.yaml
  test/integration/parse-param-operator-in-operator/00-dream.yaml
  test/integration/parse-param-operator-in-operator/01-assert.yaml
  test/integration/parse-param-operator-in-operator/01-install.yaml
Labels: kep/24, release/highlight

#847 KEP-9 and 10 Updates which includes all possible user facing YAML possibilities
  keps/0009-operator-toolkit.md
  keps/0010-package-manager.md
Labels: kind/kep

#1352 KEP-20 part 2: trigger plans manually
  cmd/manager/main.go
  config/crds/kudo.dev_instances.yaml
  go.mod
  pkg/apis/kudo/v1beta1/instance_types.go
  pkg/apis/kudo/v1beta1/instance_types_helpers.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
  pkg/kudoctl/cmd/plan.go
  pkg/kudoctl/cmd/plan/plan_history.go
  pkg/kudoctl/cmd/plan/plan_trigger.go
  pkg/kudoctl/cmd/testdata/deploy-kudo-ns.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-sa.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo-webhook.yaml.golden
  pkg/kudoctl/cmd/testdata/deploy-kudo.yaml.golden
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/kudoinit/crd/bindata.go
  pkg/kudoctl/kudoinit/prereq/prereqs.go
  pkg/kudoctl/kudoinit/prereq/webhook.go
  pkg/kudoctl/util/kudo/kudo.go
  pkg/kudoctl/util/kudo/kudo_test.go
  pkg/kudoctl/util/kudo/upgrade.go
  pkg/webhook/instance_admission.go
  pkg/webhook/instance_admission_test.go
  test/README.md
Labels: release/breaking-change, release/highlight

#1400 Fix decoding errors with large YAML templates
  pkg/engine/renderer/parser.go
  pkg/engine/renderer/parser_test.go
Labels: priority/critical, release/blocker

#1364 KEP-26: Reading parameter values from a file
  keps/20200225-reading-parameter-values-from-a-file.md
Labels: kep/26, kind/kep

#966 Add the --wait flag to install
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/install.go
  pkg/kudoctl/util/kudo/install.go
  pkg/kudoctl/util/kudo/install_test.go
Labels: Hacktoberfest, do-not-merge/hold

#1410 KEP-26: Implementation
  pkg/kudoctl/cmd/install.go
  pkg/kudoctl/cmd/install/params.go
  pkg/kudoctl/cmd/install/params_test.go
  pkg/kudoctl/cmd/params/parser.go
  pkg/kudoctl/cmd/params/parser_test.go
  pkg/kudoctl/cmd/update.go
  pkg/kudoctl/cmd/upgrade.go
Labels: kep/26, release/highlight

#1429 Update some KEP status and refresh the list.
  hack/update_kep_overview.sh
  keps/0017-pipe-tasks.md
  keps/0023-enable-disable-features.md
  keps/0024-parameter-enhancement.md
  keps/0025-template-to-yaml-function.md
  keps/0026-reading-parameter-values-from-a-file.md
  keps/README.md
Labels: kep/26
